language: node_js
sudo: false
env:
- NODE_ENV=test
before_install:
- nvm install
- travis_retry npm install -g yarn
- node --version
cache:
  yarn: true
install:
- travis_retry yarn
script:
- yarn lint
- yarn build
- yarn start # Let Lemmy run itself
branches:
  only:
  - develop
  - master
