language: node_js
sudo: false
env:
- NODE_ENV=test
before_install:
- nvm install
- travis_retry npm install -g yarn
- node --version
cache:
  yarn: true
install:
- travis_retry yarn install
script:
- yarn lint
- yarn test
- yarn build
- yarn start
branches:
  only:
  - develop
  - master
deploy:
  provider: npm
  skip_cleanup: true
  email: krzysiekmie@gmail.com
  api_key:
    secure: Gf5qTeWU05L6+zOdUQ/oGYRHtBEJgygf8rk4y4QZXX4/oj4HE/6GkyNxiMLPloJD5RVhiAMfeMJHN6fN8jbHCaZktBVRrmW1lzAhx8ImxyDy1Dn/Nz600H6228KdSjNJsmCZnJfjgmYGbKAqTeFVuGTa3WyPedn6ydqHIpodnkUTfqxP+MVkqkmzFeS9C5MW6UTQlrO2XWyOmMQSKBBQLxrRRfQIfrcmJDOY5+594s7qnL2mIpY6UYtBTH3hnyqlA2kVloXN9/3iPJjiibLHpVmbch1oP2hSMQp0fo4Um5G5AlzqdWGqvqhPrKc8OoOHo/t7RZuHO3ZFVL7d9CgtenfNOv49W+h3REcZqPNeY+Yss0dvNHFnMX+gQg508THpadr3r6V2ogIZ1Y4RyX7kIr/dF3GbPkBCCNeFYXWi8ACEOUHTDGLSZniebI4FIL2Ep/R8EsOknPgyjqXluCBCiBkRYPjLBVQJfH7deoTo6Dyji72uibsmYNRlQTPC0JiTvTnAYi5VxjZc2i784KUOGFd75prHHZWuNeIvnjJD4XLkFz0u8Did6HzjJX3geCVY79MbRQKaHYTkChZx/5hj4ByxlKBBmjC4F+fa8fvVUheGDWP3SpAfKWb61Xg2yaJazMlgd6vPPUxw2MuLtCkKdvATaU2XReMb2ZALwl/eEtA=
  on:
    branch: master
