language: node_js
sudo: false
env:
- NODE_ENV=test
before_install:
- nvm install
- travis_retry npm install -g yarn
- node --version
cache:
  yarn: true
install:
- yarn
script:
- yarn lint
- yarn build
- yarn start
branches:
  only:
  - develop
  - master
deploy:
  provider: npm
  email: krzysiekmie@gmail.com
  api_key:
    secure: WN8Lsq0yN2506H8bTFd2OlSoM5+ljnoww0aChmjzs4kTfgcu5NBeOB6aQRcazlTN+G/X40xK9wL91zjCUdRtOM6eUlp4TagBnVPspbHKSk5gEyIxnmPa1eih5OWt9wmeKRFMnqx9J/+OLFbmRCY6h6axjUnHPGpmVmyTpFj/39OOexFB6cZnkW33qIa3AyYMaaufQMKqdELdMsWa63uyMZPtzp34DUZ9kicpk8lMyVXXA+ELU256Ew0kBfawm0HStoXcXfGoN6m/Oz+ZUPRkOWrPmZKSkDUZWBqJ9vT/VaFpogGQsYocrWcEk2o0ZSaI80kagBDV80oE6zr5YCqrH1ncQe0joxrIU6Ou+mZ3hf4ZsJHjTgc5yLPev7mRDxvGsKL23GRwulkmKw9lg0JjmsRpdZXbw1b9sNFhaKWUbOj/Wqmksj+97a5Kv4zdP/pxlxD9lJumWyoThPanK8dcenyLKSVaqIO12Lj8ax95Xwaj5xIvMQmoVBsBhKc1bF2MpbSUvmYOF29DAy85TsTJm/DDfZ8bU4Vn1f3tyeKY/STwmHhJXZeMZlcotjCNSY5Jc3DV7mk82pG5NHRYQ5Qht4aXUP4r/2AbRAdjQ9UsXuZIbqKYd2zuJbJJ2R2gBVcJXjt632eCJea0VNrjXwQJcnid1CDueov465wWmXQt7Kw=
  on:
    branch: master
